out_stackdriver: Make out_stackdriver compilable with MSVC
MSVC does not support variable length arrays. For this reason,
this line raises a syntax error while compilation.

    error C2133: 'extract_latency': unknown size

Avoid that error by using a fixed buffer size.

Note: According to the spec, the max value of latency/Duration is
"315576000000.999999999s". So a 64 bytes buffer should be enough,
even if there are some white spaces prefixed.

Signed-off-by: Fujimoto Seiji <fujimoto@ceptord.net>