fluent-bit-shared: Link with -lpthread
This fixes a reference to pthread_atfork in libfluent-bit.so
otherwise we get undefined reference to the symbols in binaries
which are linked with libfluent-bit.so

Fixes errors like
arm-bec-linux-gnueabi-ld: ../../bin/hello_world: hidden symbol `pthread_atfork' in /mnt/a/oe/build/tmp/work/cortexa7t2hf-neon-vfpv4-bec-linux-gnueabi/fluentbit/0.12.1-r0/recipe-sysroot/usr/lib/libpthread_nonshared.a(pthread_atfork.oS) is referenced by DSO

Signed-off-by: Khem Raj <raj.khem@gmail.com>