ci: download WinFlexBison from GitHub instead of MSYS (#2740)
MSYS seems to be unstable. Indeed CI is currently failing with
the following error:

> warning: failed to retrieve some files
> downloading flex-2.6.4-1-x86_64.pkg.tar.xz...
> error: failed to commit transaction (unexpected error)
> Errors occurred, no packages were upgraded.
>
> https://ci.appveyor.com/project/fluent/fluent-bit-2e87g/builds/36072635

Mitigate the failure by switching to downloading WinFlexBison
from GitHub.

Signed-off-by: Fujimoto Seiji <fujimoto@ceptord.net>