network: fix an invalid reference to `u_conn` (#2811)
Windows build is failing with the following error:

    flb_network.c(243): error C2065: 'u_conn': undeclared identifier

This is because `u_conn` is not defined within the scope of this
function (net_connect_sync).

With this patch, master HEAD becomes compilable on Windows again.

Signed-off-by: Fujimoto Seiji <fujimoto@ceptord.net>