tests: internal: fix a compilation error on FLB_STREAM_PROCESSOR=Off
Right now, the following command fails with a compile error.

    $ cmake -DFLB_DEV=On -DFLB_STREAM_PROCESSOR=Off ..
    $ make
    ...
    error: struct flb_config’ has no member named ‘stream_processor_tasks

This is just due to cmake trying to compile the test suite for stream
processor even when the feature is NOT available (FLB_STREAM_PROCESSOR=Off).
This fixes it.

Signed-off-by: Fujimoto Seiji <fujimoto@clear-code.com>