flb_engine: use sb_segregate_chunks() only if in_storage_backlog provides it
Without this patch, we get this linker error:

  [100%] Linking C executable ../bin/fluent-bit
  <toolchai-path>/bin/ld: ../library/libfluent-bit.a(flb_engine.c.o): in function `flb_engine_start':
  src/platform-v7a/build-target/fluent-bit-1.8.11/src/flb_engine.c:684: undefined reference to `sb_segregate_chunks'

when fluent-bit was configured with -DFLB_IN_STORAGE_BACKLOG=Off, because in
this case the called function wasn't compiled in.

Fixes: ba58aa0783d6b5029c51f9524f0df303b2250417
Signed-off-by: Robert Schwebel <r.schwebel@pengutronix.de>