io: Avoid compilation error due to INLINE
Declaring a function as `inline` can cause the function symbol to
be invisible from the external unit.

I can confirm this behaviour on MSVC 2019 with Release build, and
it results in the following error:

    fatal error LNK2001: unresolved external symbol flb_io_net_connect

This removes `INLINE` to avoid such linking errors.

Note: All credits go to Jeremy Edwards who pointed out this bug first
on fluent-bit#2945, I just end up re-discovering his idea.

Signed-off-by: Fujimoto Seiji <fujimoto@ceptord.net>