lib: flb_libco: Fix ppc64 function arguments
This software currently does not built on Power due to duplicated
function.

  lib/flb_libco/ppc.c:282:12: error: conflicting types for 'co_create'
    cothread_t co_create(unsigned int size, void (*entry_)(void)) {

  lib/flb_libco/libco.h:19:12: note: previous declaration of 'co_create' was here
    cothread_t co_create(unsigned int, void (*)(void), size_t *);

This is happening because commit
b2bb2227cd2712df1946c438ec733b5956e9ecd8 forgot to change the function
name on ppc source code.

Signed-off-by: Breno Leitao <breno.leitao@gmail.com>