build: link shared lib with -lpthread
This fixes a reference to pthread_atfork in libfluent-bit.so
otherwise we get undefined reference to the symbols in binaries
which are linked with libfluent-bit.so

Fixes errors like
arm-bec-linux-gnueabi-ld: ../../bin/hello_world: hidden symbol `pthread_atfork'...

Signed-off-by: Khem Raj <raj.khem@gmail.com>
Signed-off-by: Eduardo Silva <eduardo@treasure-data.com>